# include ~/.config/kitty/themes/mocha.conf
map ctrl+shift+enter launch --type=tab --cwd=current

font_family "Space Mono for Powerline"
font_size 14

scrollback_lines 5000

tab_powerline_style round

notify_on_cmd_finish invisible 20

map alt+left previous_tab
map alt+right next_tab
map ctrl+shift+t new_tab
map ctrl+alt+w close_window
map ctrl+alt+x close_tab
map ctrl+shift+p show_scrollback_search

enabled_layouts splits,stack,fat,tall

# Create a new window splitting the space used by the existing one so that
# the two windows are placed one above the other
map f5 launch --location=hsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side
map f6 launch --location=vsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side if the existing window is wide or
# one above the other if the existing window is tall.
map f4 launch --location=split

# Move the active window in the indicated direction
map alt+shift+up move_window up
map alt+shift+left move_window left
map alt+shift+right move_window right
map alt+shift+down move_window down

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

# Entrar en modo redimensión con Ctrl+Alt+R
map ctrl+alt+r start_resizing_window

map ctrl+alt+z toggle_layout stack
map ctrl+alt+l next_layout

window_border_width 1pt
draw_minimal_borders yes
foreground               #cdcdcd
background               #141415
selection_foreground     #cdcdcd
selection_background     #252530
cursor                   none
url_color                #bb9dbd

active_border_color #878787
inactive_border_color #252530

color0   #252530
color8   #606079
color1   #d8647e
color9   #e08398
color2   #7fa563
color10  #99b782
color3   #f3be7c
color11  #f5cb96
color4   #6e94b2
color12  #8ba9c1
color5   #bb9dbd
color13  #c9b1ca
color6   #aeaed1
color14  #bebeda
color7   #cdcdcd
color15  #d7d7d7

active_tab_foreground    #cdcdcd
active_tab_background    #252530
inactive_tab_foreground  #606079
inactive_tab_background  #141415
