include ~/.config/kitty/themes/mocha.conf

font_family "Meslo LG S for Powerline"
font_size 12

scrollback_lines 5000

tab_powerline_style round

notify_on_cmd_finish invisible 20

map alt+left previous_tab
map alt+right next_tab
map ctrl+shift+t new_tab
map ctrl+shift+w close_current_tab
map ctrl+shift+p show_scrollback_search
